language: r
r:
  - release
  - devel
cache: packages

r_github_packages:
  - jimhester/covr

env:
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
  - Rscript -e 'covr::codecov(exclusions = list("R/zzz.R"))'
